session_name: dev
windows:
  - window_name: local
    layout: tiled
    panes:
      - yazi
  - window_name: notes
    layout: tiled
    panes:
      - vim $HOME/notes/

  - window_name: home-lab
    panes:
      - 
