session_name: dev
windows:
  - window_name: haxor-news
    layout: tiled
    panes:
      - hn best 
  - window_name: notes
    layout: tiled
    panes:
      - vim $HOME/notes/

  - window_name: files
    panes:
      - yazi
  - window_name: spotify
    panes:
      - ncspot
  - window_name: local 
    panes:
      - k9s
