session_name: dev
windows:
  - window_name: local
    layout: tiled
    panes:
      - 
  - window_name: notes
    layout: tiled
    panes:
      - vim $HOME/notes/

  - window_name: files
    panes:
      - yazi
  - window_name: spotify
    panes:
      - ncspot
