# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
foreground = "#f8f8f2"
background = "#282a36"

[colors.selection]
background = "#3e4452"
text = "#abb2bf"

[colors.normal]
white = "#abb2bf"
red = "#ff5555"
green = "#50fa7b"
cyan = "#8be9fd"
yellow = "#f1fa8c"
blue = "#bd93f9"
black = "#191a21"
magenta = "#ff79c6"

[colors.cursor]
cursor = "#f8f8f2"
text = "#282a36"

[colors.bright]
white = "#ffffff"
red = "#ff6e6e"
green = "#69ff94"
cyan = "#a4ffff"
yellow = "#ffffa5"
blue = "#d6acff"
black = "#44475a"
magenta = "#ff92df"
