# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.selection]
text = "#fdfbee"
background = "#484844"

[colors.bright]
yellow = "#ffffb6"
blue = "#96cbfe"
white = "#fdfbee"
magenta = "#ff73fd"
green = "#a8ff60"
cyan = "#c6c5fe"
black = "#6c6c66"
red = "#ff6c60"

[colors.primary]
background = "#000000"
foreground = "#b5b3aa"

[colors.normal]
yellow = "#ffffb6"
blue = "#96cbfe"
white = "#b5b3aa"
magenta = "#ff73fd"
green = "#a8ff60"
cyan = "#c6c5fe"
black = "#000000"
red = "#ff6c60"

[colors.cursor]
text = "#000000"
cursor = "#b5b3aa"
