# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
foreground = "#c5c9c5"
background = "#181616"

[colors.cursor]
cursor = "#c5c9c5"
text = "#181616"

[colors.bright]
red = "#e46876"
green = "#87a987"
yellow = "#e6c384"
cyan = "#7aa89f"
magenta = "#938aa9"
white = "#c5c9c5"
blue = "#7fb4ca"
black = "#a6a69c"

[colors.selection]
background = "#223249"
text = "#c5c9c5"

[colors.normal]
red = "#c4746e"
green = "#8a9a7b"
yellow = "#c4b28a"
cyan = "#8ea4a2"
magenta = "#a292a3"
white = "#c8c093"
blue = "#8ba4b0"
black = "#0d0c0c"
