# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.normal]
red = "#bd8183"
cyan = "#7b9695"
yellow = "#e49b5d"
white = "#c1a78e"
magenta = "#b380b0"
green = "#78997a"
black = "#34302c"
blue = "#7f91b2"

[colors.bright]
red = "#d47766"
cyan = "#89b3b6"
yellow = "#ebc06d"
white = "#ece1d7"
magenta = "#cf9bc2"
green = "#85b695"
black = "#867462"
blue = "#a3a9ce"

[colors.selection]
background = "#403a36"
text = "#c1a78e"

[colors.primary]
background = "#292522"
foreground = "#ece1d7"

[colors.cursor]
cursor = "#ece1d7"
text = "#292522"
