# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.bright]
black = "#727072"
white = "#fcfcfa"
cyan = "#78dce8"
blue = "#fc9867"
green = "#a9dc76"
red = "#ff6188"
yellow = "#ffd866"
magenta = "#ab9df2"

[colors.cursor]
cursor = "#fcfcfa"
text = "#fcfcfa"

[colors.normal]
black = "#221f22"
white = "#fcfcfa"
cyan = "#78dce8"
blue = "#fc9867"
green = "#a9dc76"
red = "#ff6188"
yellow = "#ffd866"
magenta = "#ab9df2"

[colors.primary]
background = "#2d2a2e"
foreground = "#fcfcfa"

[colors.selection]
text = "#fcfcfa"
background = "#434043"
