
[colors.bright]
blue = "#81a1c1"
red = "#bf616a"
cyan = "#88c0d0"
yellow = "#ebcb8b"
magenta = "#b48ead"
green = "#a3be8c"
black = "#4c566a"
white = "#8fbcbb"

[colors.cursor]
text = "#2e3440"
cursor = "#e5e9f0"

[colors.normal]
blue = "#81a1c1"
red = "#bf616a"
cyan = "#88c0d0"
yellow = "#ebcb8b"
magenta = "#b48ead"
green = "#a3be8c"
black = "#2e3440"
white = "#e5e9f0"

[colors.primary]
background = "#2e3440"
foreground = "#e5e9f0"

[colors.selection]
text = "#2e3440"
background = "#434c5e"
